version: "3.9"

services:

  field-agent-api:
    build: ./field-agent-api
    image: austinf/field-agent-api
    environment:
      - DB_URL=jdbc:mysql://board-game-db:3306/field_agent
      - DB_USERNAME=root
      - DB_PASSWORD=top-secret-passowrd
    ports:
      - "8080:8080"
    depends_on:
      - field-agent-db

  field-agent-db:
    build: ./database
    image: austinf/field-agent-db
    volumes:
      - field-agent-data:/var/lib/mysql

volumes:
  field-agent-data: